"""modifications

Revision ID: 318fe9fe0926
Revises: b65d321b1006
Create Date: 2025-04-16 00:14:18.423065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318fe9fe0926'
down_revision = 'b65d321b1006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_text', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('option_a', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('option_b', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('option_c', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('option_d', sa.String(length=200), nullable=False))
        batch_op.drop_column('question_statement')
        batch_op.drop_column('question_title')
        batch_op.drop_column('option3')
        batch_op.drop_column('option1')
        batch_op.drop_column('option2')
        batch_op.drop_column('option4')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option4', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('option2', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('option1', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('option3', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('question_title', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('question_statement', sa.TEXT(), nullable=False))
        batch_op.drop_column('option_d')
        batch_op.drop_column('option_c')
        batch_op.drop_column('option_b')
        batch_op.drop_column('option_a')
        batch_op.drop_column('question_text')

    # ### end Alembic commands ###
